/* generated by tools/build_elf_page.py - do not edit */
window.PAYLOAD_TILES = [
    { title: "ftpsrv", description: "FTP server. Runs on port 2121.", name: "ftpsrv-ps5.elf", key: "ftp" },
    { title: "pldmgr", description: "Payload Manager.", name: "klogsrv-ps5.elf", key: "klog" }
];
window.PAYLOAD_ART = { dir: "ui/", pfx: "btn-", on: true };
